[phases.setup]
nixPkgs = ["openjdk21"]

[phases.build]
cmds = ["./gradlew clean build -x check -x test"]

[start]
cmd = "java -XX:ActiveProcessorCount=2 -Xms32m -Xmx512m -XX:+UseG1GC -jar build/libs/braggly.jar"
