#!/bin/bash

# Ustawienia
BASE_URL="http://localhost:9191"
USERNAME="admin"
PASSWORD="admin"

# 1. Pobranie tokena
TOKEN=$(curl -s -X POST "$BASE_URL/api/auth/login" \
  -H "Content-Type: application/json" \
  -d "{\"username\": \"$USERNAME\", \"password\": \"$PASSWORD\"}" | jq -r '.token')

if [ "$TOKEN" == "null" ] || [ -z "$TOKEN" ]; then
    echo "❌ Błąd: Nie udało się pobrać tokena!"
    exit 1
fi

echo "Authentication token received"

# 3. Dodanie pakietu kredytowego
NEW_PACKAGE='{"credits": 10, "priceInCents": 888}'
RESPONSE=$(curl -s -v -X POST "$BASE_URL/credits/packages"  -H "Authorization: Bearer $TOKEN"  -H "Content-Type: application/json"  -d "$NEW_PACKAGE")
echo "🆕 Odpowiedź z dodania pakietu: $RESPONSE"

